import os
from dotenv import load_dotenv
from string import ascii_uppercase
from utils import DataSource, TextDataSource,JsonDataSource, APIDataSource


def conditional(operand_1: int, operator: str, operand_2: int) -> bool:
    """
    Evaluates a logical condition between two operands based on the provided
    string operator (e.g., '==', '>=', '<=', '!=', '>', '<') and returns a boolean result.[cite: 2]
    """
    if "==" in operator:
        return operand_1 == operand_2
    elif ">=" in operator:
        return operand_1 >= operand_2
    elif "<=" in operator:
        return operand_1 <= operand_2
    elif "!=" in operator:
        return operand_1 != operand_2
    elif ">" in operator:
        return operand_1 > operand_2
    else:
        return operand_1 < operand_2


def value(x: int, data: dict) -> int:
    """
    Retrieves the value of a register from the data dictionary if 'x' exists as a key;
    otherwise, it attempts to convert 'x' to an integer and returns it.
    """
    if x in data:
        return data[x]
    return int(x)


def run(raw_data: DataSource) -> list:
    """
    Parses commands from the provided DataSource and acts as a basic interpreter to execute
    instructions (MOV, ADD, MUL, SUB, PRINT, JUMP, IF, END).
    Returns a list of all outputted values generated by the 'PRINT' commands.
    """
    commands = raw_data.parse_file()
    print_list = []
    characters = ascii_uppercase
    data = {i: 0 for i in ascii_uppercase}
    row = 0

    while True:
        if row == len(commands):
            break

        parts = commands[row].split(" ")

        if parts[0] == "MOV":
            data[parts[1]] = value(parts[2], data)
        elif parts[0] == "ADD":
            data[parts[1]] += value(parts[2], data)
        elif parts[0] == "MUL":
            data[parts[1]] *= value(parts[2], data)
        elif parts[0] == "SUB":
            data[parts[1]] -= value(parts[2], data)
        elif parts[0] == "PRINT":
            print_list.append(value(parts[1], data))
        elif parts[0] == "JUMP":
            row = commands.index(f"{parts[1]}:")
        elif "IF" in parts:
            if conditional(value(parts[1], data), parts[2], value(parts[3], data)):
                row = commands.index(f"{parts[5]}:")

        if "END" in parts:
            break

        row += 1

    return print_list


if __name__ == "__main__":
    load_dotenv()
    raw_data = APIDataSource(os.getenv("ENDPOINT_URL"))
    print(run(raw_data))
